name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://user:pass@localhost:5433/db?schema=public
      PORT: 3000
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Generate OpenAPI types
        run: npm run openapi:all

      - name: Lint
        run: npx nx run-many -t lint --all

      - name: Unit Tests
        run: npx nx run-many -t test --all --coverage

      - name: Build Backend (with deps)
        run: npx nx build backend --with-deps

      - name: Build Frontend
        run: npx nx build frontend

      - name: Backend E2E (smoke)
        run: npx nx e2e backend-e2e --ci

      - name: Frontend E2E (smoke)
        run: npx nx e2e frontend-e2e --ci

      - name: Archive dist
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
          if-no-files-found: warn
