name: Deploy Backend (VPS)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'libs/**'
      - 'tools/docker/**'
      - 'docker-compose.deploy.yml'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/deploy-backend.yml'

concurrency:
  group: deploy-backend-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BACKEND: ${{ github.repository }}-backend
  # GHCR PAT para docker login en el VPS
  GHCR_PAT: ${{ secrets.GHCR_PAT }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: tools/docker/Dockerfile.backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}:${{ github.sha }}

      - name: Persist image tags
        id: meta
        run: |
          echo "BACKEND_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}:${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure deploy path exists
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script_stop: true
          script: |
            mkdir -p "${{ secrets.DEPLOY_PATH }}"

      - name: Copy compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: |
            docker-compose.deploy.yml
          target: ${{ secrets.DEPLOY_PATH }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script_stop: true
          envs: GHCR_PAT,GITHUB_ACTOR
          script: |
            set -e
            cd ${{ secrets.DEPLOY_PATH }}
            # Docker login en GHCR para pulls privados
            echo "${GHCR_PAT}" | docker login ghcr.io -u "${GITHUB_ACTOR}" --password-stdin
            # Archivo .env.deploy con la imagen de backend
            echo BACKEND_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}:${{ github.sha }} > .env.deploy

            # Pull de servicios necesarios
            docker compose --env-file .env --env-file .env.deploy -f docker-compose.deploy.yml pull db backend || true

            # DB primero
            docker compose --env-file .env --env-file .env.deploy -f docker-compose.deploy.yml up -d db
            echo "Esperando DB saludable..."
            for i in $(seq 1 60); do
              if docker compose --env-file .env --env-file .env.deploy -f docker-compose.deploy.yml exec -T db pg_isready -U ${POSTGRES_USER:-postgres} ; then
                echo "DB lista"; break; fi; sleep 2; done

            # Migraciones y seed opcional
            echo "Prisma migrate deploy..."
            docker compose --env-file .env --env-file .env.deploy -f docker-compose.deploy.yml run --rm backend npx prisma migrate deploy --schema=/app/prisma/schema.prisma
            echo "Verificando necesidad de seed..."
            NEED_SEED=$(docker compose --env-file .env --env-file .env.deploy -f docker-compose.deploy.yml exec -T db psql -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-cms} -tAc "SELECT CASE WHEN EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='User') THEN (SELECT CASE WHEN (SELECT COUNT(*) FROM \"User\")=0 THEN 'yes' ELSE 'no' END) ELSE 'yes' END;")
            if [ "$NEED_SEED" = "yes" ]; then
              echo "Prisma db seed..."
              docker compose --env-file .env --env-file .env.deploy -f docker-compose.deploy.yml run --rm backend npx prisma db seed --schema=/app/prisma/schema.prisma
            else
              echo "Seed no necesario."
            fi

            # Levantar/actualizar backend solamente
            docker compose --env-file .env --env-file .env.deploy -f docker-compose.deploy.yml up -d db backend
            docker image prune -f || true
